ChinaDaily/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('news/', include('news.urls', namespace='news')),
]

news/urls.py
from django.urls import path
from . import views

app_name = 'news'

urlpatterns = [
    path('news-list/', views.news_list, name='news-list'),
    path('news-import/', views.news_import, name='news-import'),
    path('news-download/', views.news_download, name='news-download'),
    path('news-trend/', views.news_trend, name='news-trend'),
    path('news-real-time-input/', views.news_real_time_input, name='news-real-time-input'),
    path('news-real-time-result/', views.news_real_time_result, name='news-real-time-result')
]

news/models.py
from django.db import models

# Create your models here.
from django.utils import timezone


class News(models.Model):
    title = models.TextField()
    content = models.TextField()

    add_time = models.DateField(default=timezone.now)

    positive = models.IntegerField()
    neutral = models.IntegerField()
    negative = models.IntegerField()

news/views.py
from django.http import HttpResponse
from django.shortcuts import render, redirect
from .sparkTools.emotion_analysis import news_emotion_analysis_by_file, news_emotion_analysis_by_text
from .sparkTools.test_crawler import crawl
from .models import News
import os
from django.db.models import Avg
# Create your views here.


# 新闻首页（列表）：可通过date和type两个属性进行筛选
def news_list(request):
    date = request.GET.get('date')
    type = request.GET.get('type')
    news_list = News.objects.all().order_by('-add_time')
    if date != "" and date != None:
        news_list = news_list.filter(add_time=date)

    # 将某种情感占比大于40%的新闻定义为改种情感类型的新闻
    if type != "" and type != None:
        if type == 'positive':
            news_list = news_list.filter(positive__gte=40).order_by('-positive')
        if type == 'negative':
            news_list = news_list.filter(negative__gte=40).order_by('-negative')
        if type == 'neutral':
            news_list = news_list.filter(negative__gte=40).order_by('-neutral')
    context = {'news_list': news_list, 'date': date, 'type': type}
    return render(request, 'news/news-list.html', context)


# 导入新闻以及其情感分析结果至数据库中
def news_import(request):
    date = request.GET.get('date')
    dict_path = 'static/news/'+str(date)
    files = os.listdir(dict_path)

    # 分析当日所有新闻情感构成
    # 导入结果到数据库中
    for file in files:
        emotion_proportion, content = news_emotion_analysis_by_file(dict_path + '/' + file)

        news = News(title=file.replace('.txt', ''),
                    content = content,
                    positive = emotion_proportion['positive'],
                    negative = emotion_proportion['negative'],
                    neutral = emotion_proportion['neutral']
        )
        news.save()

    return redirect('news:news-list')


# 下载当日新闻到本地
def news_download(request):
    # 调用爬虫函数将当日新闻下载到本地指定文件夹中
    crawl()
    return HttpResponse('Success!')


# 分析近日新闻情感趋势
def news_trend(request):
    daily_proportion_list = News.objects.values('add_time').annotate(
        positive_score = Avg('positive'),
        neutral_score = Avg('neutral'),
        negative_score = Avg('negative')
    )
    # 获取数据库中所有新闻的日期,根据不同日期进行分组（group操作）
    time_list = list(daily_proportion_list.values_list('add_time', flat=True))
    time_list = [str(i).replace('&#39', '') for i in time_list]


    context = {'time_list': time_list,
               'positive_list': list(daily_proportion_list.values_list('positive_score', flat=True)),
               'neutral_list': list(daily_proportion_list.values_list('neutral_score', flat=True)),
               'negative_list': list(daily_proportion_list.values_list('negative_score', flat=True))}

    # 前端接受各个参数用于绘制情感构成直方图
    return render(request, 'news/news-trend.html', context)


# 导航至实时分析情感构成界面
def news_real_time_input(request):
    return render(request, 'news/news-real-time-input.html')


# 获取用户输入的英文文本，调用文本分析函数获取情感构成
def news_real_time_result(request):
    news = request.POST.get('news')

    emotion_proportion, _ = news_emotion_analysis_by_text(news)

    context = {'news': news, 'emotion_proportion': emotion_proportion}

    return render(request, 'news/news-real-time-result.html', context)

templates/base.html
{% load staticfiles %}

<!DOCTYPE html>
<html lang="zh-cn">

<head>
    <meta charset="utf-8">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.min.css' %}">
</head>

<body>
    {% include 'header.html' %}
    {% block content %}{% endblock content %}
    {% include 'footer.html' %}
    <script src="{% static 'jquery/jquery-3.3.1.js' %}"></script>

    <script src="{% static 'layer/layer.js' %}"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1-lts/dist/umd/popper.min.js"></script>

    <script src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>
    <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap-datetimepicker.min.css' %}">
    <script src="{% static 'bootstrap/js/bootstrap-datetimepicker.js' %}"></script>
    <script src="{% static 'bootstrap/js/bootstrap-datetimepicker.zh-CN.js' %}"></script>

</body>

</html>

templates/footer.html
{% load staticfiles %}
<!-- Footer -->
<div>
    <br><br><br>
</div>
<footer class="py-3 bg-dark fixed-bottom">
    <div class="container">
{#        <p class="m-0 text-center text-white">如有问题，请联系负责人<b>陶晨阳</b> | QQ：<b>871391952</b> | 电话（微信同）：<b>19825300927</b></p>#}

        <p class="m-0 text-center text-white">Copyright &copy; patrickdd</p>
    </div>
</footer>

templates/header.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container">
{#  {% load staticfiles %}#}
{#  <img src="{% static 'image/head.png' %}" width="250px" height="40px">#}
    <a class="navbar-brand" href="{% url 'news:news-list' %}">Emotion&nbsp;&nbsp;&nbsp;Analysis&nbsp;&nbsp;&nbsp;of&nbsp;&nbsp;&nbsp;China&nbsp;&nbsp;&nbsp;Daily</a>

    <div>
      <ul class="navbar-nav">
        <li class="nav-item">
        </li>
        <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              More
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                {% now "Y-m-d" as date%}
                <a class="dropdown-item" href="{% url 'news:news-download' %}">Download Today's News</a>

                <a class="dropdown-item" href="{% url 'news:news-import' %}?date={{ date }}">Import Today's News</a>

                <a class="dropdown-item" href="{% url 'news:news-trend' %}">Analysis of News Trend</a>

                <a class="dropdown-item" href="{% url 'news:news-real-time-input' %}">Real-Time Analysis of News</a>
            </div>
        </li>

      </ul>
    </div>

  </div>
</nav>

templates/news/news-list.html
{% extends "base.html" %}
{% load staticfiles %}

{% block title %}
    News List
{% endblock title %}

{% block content %}
    {#    <link rel="stylesheet" href="https://cdn.staticfile.org/twitter-bootstrap/3.3.7/css/bootstrap.min.css">#}


    <div class="container">
        <br>
        <div class="row">
            {#            <div class="col-auto mr-auto">#}
            <form class="form-inline">
                <div class="form-group mx-sm-3 mb-2">
                    <label for="date" class="sr-only">date</label>
                    <input type="date" class="form-control" id="date" placeholder="date" name="date" value="{{ date }}">
                </div>
                {#                <div class="form-group mx-sm-3 mb-2">#}
                {#                    <label for="type" class="sr-only">type</label>#}
                {#                    <input type="text" class="form-control" id="type" placeholder="type" name="type" value="{{ type }}">#}
                {#                </div>#}
                <div class="form-group mx-sm-3 mb-2">
                    <label for="type" class="sr-only">type</label>
                    <select class="form-control" id="type" name="type">
                        <option value="{{ type }}">{{ type }}</option>

                        <option value="none">none</option>

                        <option value="positive">positive</option>
                        <option value="neutral">neutral</option>
                        <option value="negative">negative</option>

                    </select>
                </div>


                <button type="submit" class="btn btn-primary mb-2">Search</button>
            </form>
            {#            </div>#}
        </div>
        <br>

        {#    <hr>#}

        {#    {% now "Y-m-d" as date%}#}
        {#        <a class="btn btn-primary" href="{% url 'news:news-download' %}">Download Today's News</a>#}
        {##}
        {#        <a class="btn btn-primary" href="{% url 'news:news-import' %}?date={{ date }}">Import Today's News</a>#}
        {##}
        {#        <a class="btn btn-primary" href="{% url 'news:news-trend' %}">Analysis of News Trend</a>#}
        {#        <br>#}
        <h2>All : {{ news_list.count }} News</h2>

        <br>
        {#        <hr>#}
        <div class="row mt-2">

            {% for news in news_list %}
                <div class="col-4 mb-4">
                    <div class="card h-100">
                        <h4 class="card-header">{{ news.title|slice:'50' }}...</h4>
                        <div class="card-body">
                            <p class="card-text">{{ news.content|slice:'100' }}...</p>
                        </div>
                        <div class="card-footer">
                            <div class="progress">
                                <div class="progress-bar bg-success progress-bar-striped" role="progressbar"
                                     aria-valuenow="20"
                                     aria-valuemin="0" aria-valuemax="100"
                                     style="width:{{ news.positive }}%">{{ news.positive }}%
                                </div>
                                <div class="progress-bar bg-warning progress-bar-striped" role="progressbar"
                                     aria-valuenow="20"
                                     aria-valuemin="0" aria-valuemax="100"
                                     style="width:{{ news.neutral }}%">{{ news.neutral }}%
                                </div>
                                <div class="progress-bar bg-danger progress-bar-striped" role="progressbar"
                                     aria-valuenow="20"
                                     aria-valuemin="0" aria-valuemax="100"
                                     style="width:{{ news.negative }}%">{{ news.negative }}%
                                </div>

                            </div>
                            {#                                    <a href="#" class="btn btn-primary">进入</a>#}

                        </div>
                    </div>
                </div>
            {% endfor %}

        </div>
    </div>


{% endblock content %}

templates/news/news-real-time-input.html
{% extends "base.html" %}
{% load staticfiles %}

{% block title %}
    News Real-Time Analysis Input
{% endblock title %}

{% block content %}

    <div class="container">

        <div class="col-12">
            <br>
            <h4>Input the News , then Get the Emotion Analysis!</h4>
            <br>

            <form action="{% url 'news:news-real-time-result' %}" method="POST">
                {% csrf_token %}
                <div class="form-group">
                    <textarea type="text" class="form-control" id="news" name="news" rows="15">{{ news }}</textarea>
                </div>
                <button type="submit" class="btn btn-primary ">Analyze</button>
            </form>
        </div>
        <br>

        <br>

    </div>

{% endblock %}

templates/news/news-real-time-result.html
{% extends "base.html" %}
{% load staticfiles %}

{% block title %}
    News Real-Time Analysis Result
{% endblock title %}

{% block content %}

    <div class="container">
        <br>
        <div class="col-12">
            <h4>Emotion Analysis of News</h4>
            <div class="progress">
                <div class="progress-bar bg-success progress-bar-striped" role="progressbar" aria-valuenow="20"
                     aria-valuemin="0" aria-valuemax="100"
                     style="width:{{ emotion_proportion.positive }}%">positive:{{ emotion_proportion.positive }}%
                </div>
                <div class="progress-bar bg-warning progress-bar-striped" role="progressbar" aria-valuenow="20"
                     aria-valuemin="0" aria-valuemax="100"
                     style="width:{{ emotion_proportion.neutral }}%">neutral:{{ emotion_proportion.neutral }}%
                </div>
                <div class="progress-bar bg-danger progress-bar-striped" role="progressbar" aria-valuenow="20"
                     aria-valuemin="0" aria-valuemax="100"
                     style="width:{{ emotion_proportion.negative }}%">negative:{{ emotion_proportion.negative }}%
                </div>

            </div>
        </div>

        <br>
        <br>


        <div class="col-12">

            <h4>Content of News</h4>

            {{ news }}


        </div>

    </div>

{% endblock %}

templates/news/news-trend.html
{% extends "base.html" %}
{% load staticfiles %}

{% block title %}
    Analysis of News Trend
{% endblock title %}

{% block content %}
{#{{ time_list }}#}
{#{% for daily_proportion in daily_proportion_list %}#}
{#    <p>{{ daily_proportion.add_time}}</p>#}
{#    <p>{{ daily_proportion.positive_score }}</p>#}
{#    <p>{{ daily_proportion.neutral_score }}</p>#}
{#    <p>{{ daily_proportion.negative_score }}</p>#}
{#{% endfor %}#}

    <script src="{% static 'Chart/chart.min.js' %}"></script>
    <br>
<h1 align="center">Analysis of News Trend</h1>
    <br>
<div style="width:800px;margin:0px auto">
    <canvas id="myChart" ></canvas>
</div>
<script>
var ctx = document.getElementById('myChart').getContext('2d');
var myChart = new Chart(ctx, {
    type: 'bar',
    data: {
        {#labels: ['a', 'b', 'c'],#}
        labels:{{ time_list |safe}},
        datasets: [
       {
            label: 'Positive %',
            data: {{ positive_list }},
            borderColor:'blue',
            backgroundColor:'skyBlue',
            borderWidth: 1,
            yAxisID: 'y-axis-1',
        },
       {
            label: 'Neutral %',
            data: {{ neutral_list }},
            borderColor:'yellow',
            backgroundColor:'orange',
            borderWidth: 1,
            yAxisID: 'y-axis-2',
        },
            {
            label: 'Negative %',
            data: {{ negative_list }},
            borderColor:'red',
            backgroundColor:'pink',
            borderWidth: 1,
            yAxisID: 'y-axis-3',
        },

]
    },
    options:{
        scales:{
						yAxes: [
						    {
							type: 'linear',
							display: true,
							position: 'left',
							id: 'y-axis-1',
						    },
                            {
							type: 'linear',
							display: true,
							position: 'right',
							id: 'y-axis-2',
							gridLines: {
								drawOnChartArea: false
							    }
						    },
                            {
							type: 'linear',
							display: true,
							position: 'right',
							id: 'y-axis-3',
							gridLines: {
								drawOnChartArea: false
							    }
						    }
                        ],

        }
    }
});
</script>


{% endblock %}